---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-gateway-api-deploy
  namespace: linkerd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-gateway-api
  template:
    metadata:
      labels:
        app: product-gateway-api
    spec:
      containers:
      - name: product-gateway-api
        image: ggplayground.azurecr.io/product-gateway-api:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: Product_API_Host
          value: http://product-api-svc.linkerd-test:9090
        - name: Price_API_Host
          value: http://price-api-svc.linkerd-test:8080
---
apiVersion: v1
kind: Service
metadata:
  name: product-gateway-api-svc
  namespace: linkerd-test
spec:
  type: LoadBalancer
  selector:
    app: product-gateway-api
  ports:
  - port: 80
    targetPort: http